name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração da animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: f0nseca7
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "🐍 Atualizando animação do Snake"
          add: "dist/github-contribution-grid-snake.svg"
